name: Python Continuous Integration

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12

      - name: Install linting dependencies
        run: pip install pre-commit==3.8.0

      - name: Run Pre-commit - manual
        env:
          PRE_COMMIT_COLOR: always
        run: pre_commit run --all-files --hook-stage manual --verbose
